# Generated by Django 5.2.1 on 2026-01-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="downloads",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="song",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
