# Generated by Django 5.2.1 on 2026-01-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0002_song_downloads_song_views"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artist",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="song",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.AlterField(
            model_name="artist",
            name="slug",
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
